### ISSUE TITLE
Edit readME according to the instruction

### ISSUE THREAD

**Issue by Phurinat-Musikanon-6509650658** [Phurinat-Musikanon-6509650658/CS360foodadvisor#30]
- [x] แก้ไขในส่วน ReadME sprint1
- [x] แก้ไขในส่วนของ ReadME sprint2
*** เน้นแก้ไขตาม Rubric ***

**Comment by thanadech6509650435** [comment]
แก้ตาม rubic 1.1 ,1.3

**Comment by Phurinat-Musikanon-6509650658** [comment]
แก้ไข Rubric ในส่วน readME ครบหมดแล้ว
